//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.11 at 04:00:20 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ivoa.net/xml/VOTable/v1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package eu.heliovo.hec.votable;
